### ISSUE TITLE
Non-descriptive variable names

### ISSUE THREAD

**Issue by hlixed** [MissingNO123/GCIR#1]
I like what you've done; glad to see you got pygame working! 

It appears that lines 123 and 124 of gamepad.py contain variables whose names don't describe the values they hold. This, of course, is unpythonic. `button` might be a better loop counter, or perhaps `input` if you want to generalize.

You may also be interested in this neat article called [How to Write a Git Commit Message](https://chris.beams.io/posts/git-commit/); it's actually quite good.

**Comment by MissingNO123** [comment]
Sorry about that, that was at like 3AM and I was too tired to think properly
