### ISSUE TITLE
ImportError: No module named TPPFLUSH.tppflush

### ISSUE THREAD

**Issue by Moire9** [MissingNO123/GCIR#6]
The title says it all. When running it, it gives that error. I'm on Mac.
EDIT: WHAT THE HELL? When I dropped the image into the selection box, it...well it uploaded screenshots of a reddit post about TheCruel.

Let's try again:

![screen shot 2017-10-04 at 19 05 20](https://user-images.githubusercontent.com/31591796/31208220-17d51862-a938-11e7-84df-f2a01f0e076c.png)

**Comment by MissingNO123** [comment]
This isn't an issue, you're missing the TPPFLUSH folder. Please download the zip file from the [Releases Page](https://github.com/MissingNO123/GCIR/releases)

**Comment by Moire9** [comment]
Oh, I had downloaded the source by mistake, which had the TPPFLUSH @somelongnumber folder. Thanks, that hadn't occurred to me.

**Comment by Moire9** [comment]
It still happens, using the release.
Image:
![screen shot 2017-10-05 at 07 24 48](https://user-images.githubusercontent.com/31591796/31232487-dc175738-a99e-11e7-8a65-7249d9efb7cf.png)

**Comment by MissingNO123** [comment]
What version of Python do you have installed? You need Python v3.6 or higher.
Check with `python --version` because even if you have python3 installed, the command line can sometimes use python2

**Comment by Moire9** [comment]
Ah, I see. Thanks. I'll check when I'm home and have access to my Mac.

**Comment by SirNapkin1334** [comment]
I installed python 3.6.3, but on the shell it still says 2.7. How can I get the shell to use a newer version?

**Comment by SirNapkin1334** [comment]
It can't find module PyGame. I know python, but I've never even heard of that module, so I can't troubleshoot it.

**Comment by Moire9** [comment]
It's working! But, when I try to add ZL to the list of KeyBinds,
please wait...
Traceback (most recent call last):
  File "gamepad.py", line 21, in <module>
    HIDButtons.ZL,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/enum.py", line 324, in 
__ getattr __
    raise AttributeError(name) from None
AttributeError: ZL
Same for ZR. I know it doesn't really matter since I'm on o3DS, but I want to have the triggers bound to something, even if it won't do anything, so that if I accidentally press one it'll just do nothing rather than having the program freak out and crash because it had no binding.

**Comment by MissingNO123** [comment]
ZL and ZR are part of the N3DS_Buttons class (as they're not technically HID buttons) so you'd have to map them as N3DS_Buttons.ZR / .ZL

**Comment by Moire9** [comment]
Thanks! I'm having the same issue with POWER and HOME.

**Comment by MissingNO123** [comment]
POWER and HOME are under Special_Buttons

**Comment by Moire9** [comment]
I see. Thanks.

**Comment by Moire9** [comment]
Is there a way to have it, when a button is held, it sends the input over and over? Your program can tell when a button has been released, so I'm sure that's not too hard. Knowing python, I'll see if I can program it in. If I'm successful. I'll fork it.

**Comment by Moire9** [comment]
Is there a way to have it, when a button is held, it sends the input over and over? Your program can tell when a button has been released, so I'm sure that's not too hard. Knowing python, I'll see if I can program it in. If I'm successful. I'll fork it.

**Comment by Moire9** [comment]
I have had partial success, but there are some issues that I don't quite understand. Namely, whenever I press a button, it says "Pressed Button {button}" a ton and then gives me a buffer error.  
![screen shot 2017-10-06 at 10 05 08](https://user-images.githubusercontent.com/31591796/31289722-a3f759b2-aa7e-11e7-96b0-7ab2fbcd75b9.png)
I encircled in black what I changed and encircled in red what I thought was causing the issue.

**Comment by MissingNO123** [comment]
You're sending button inputs too fast, it's overloading whatever buffer Python is using for the socket connection.

Though, you did remind me that I forgot to make it optional whether it shows which gamepad buttons are pressed.

**Comment by Moire9** [comment]
I see. Is there a way to get it to "hold" a button instead of well, spamming it?

**Comment by MissingNO123** [comment]
```python
server.press(buttonMappings[event.button])
server.send(print_bytes)
```
Don't use the `server.unpress()` function since that un-presses the button.

**Comment by Moire9** [comment]
Alright. Thanks.

**Comment by Moire9** [comment]
Is there a way to massively expand/allocate more memory to buffer size?

**Comment by MissingNO123** [comment]
https://stackoverflow.com/a/38195355

**Comment by hlixed** [comment]
Just so you know, if you repeat the server.send() inside a `while` loop, like you're doing now, you'll quickly overload the buffer _and_ it won't press multiple times. The way InputRedirection works, a `server.send()` makes the 3DS keep pressing whatever configuration of buttons is sent until a new `send()` comes along, so `send()`ing a second time without pressing/unpressing any new buttons will do nothing.

If you want to press a button repeatedly, you'll want to use `server.press()`, `server.send()`, wait a little bit with `time.sleep()`, and then `server.unpress()` and `server.send()` before `time.sleep()`ing a bit more.

**Comment by Moire9** [comment]
Yes, but is there a way to _hold_ a button down?

**Comment by hlixed** [comment]
Yes.
> The way InputRedirection works, a server.send() makes the 3DS keep pressing whatever configuration of buttons is sent until a new send() comes along, so send()ing a second time without pressing/unpressing any new buttons will do nothing.

If you server.send() a button press, then wait 5 seconds without server.send()ing, the button will remain pressed for all 5 seconds. TPPFLUSH will keep holding the button until it is `unpress()`ed.

**Comment by Moire9** [comment]
Oh. I see.
